### PR TITLE
add comment to identify the source datapackages

### PR DESCRIPTION
**Pull request by OriHoch**

### CODE REVIEW

**Comment by akariv** [comment]
Please explain...

**Comment by akariv** [comment]
(also note the `dpp:streamedFrom` property in each of the datapackages under `http://next.obudget.org/datapackages/budgetkey/`

**Comment by OriHoch** [comment]
I think it's useful to have a list of the source datapackages used by the search API 

i used the dpp:streamfrom to make this list, but it takes a bit of work to get this list of all the source packages, so I thought it will be useful

**Comment by OriHoch** [comment]
also, it's useful for ppl working on budgetkey-data-pipelines which might not be familiar with the search API and which packages are used by it

**Comment by OriHoch** [comment]
@akariv updated the comment

**Pull request merged**
